<?php

return [
    'countries' => [
        ['code' => 'US', 'name' => 'United States', 'currency' => 'USD'],
        ['code' => 'GB', 'name' => 'United Kingdom', 'currency' => 'GBP'],
        ['code' => 'IN', 'name' => 'India', 'currency' => 'INR'],
        ['code' => 'AU', 'name' => 'Australia', 'currency' => 'AUD'],
        ['code' => 'CA', 'name' => 'Canada', 'currency' => 'CAD'],
        ['code' => 'DE', 'name' => 'Germany', 'currency' => 'EUR'],
        ['code' => 'FR', 'name' => 'France', 'currency' => 'EUR'],
        ['code' => 'IT', 'name' => 'Italy', 'currency' => 'EUR'],
        ['code' => 'ES', 'name' => 'Spain', 'currency' => 'EUR'],
        ['code' => 'NL', 'name' => 'Netherlands', 'currency' => 'EUR'],
        ['code' => 'JP', 'name' => 'Japan', 'currency' => 'JPY'],
        ['code' => 'CN', 'name' => 'China', 'currency' => 'CNY'],
        ['code' => 'SG', 'name' => 'Singapore', 'currency' => 'SGD'],
        ['code' => 'AE', 'name' => 'United Arab Emirates', 'currency' => 'AED'],
        ['code' => 'SA', 'name' => 'Saudi Arabia', 'currency' => 'SAR'],
        ['code' => 'BR', 'name' => 'Brazil', 'currency' => 'BRL'],
        ['code' => 'MX', 'name' => 'Mexico', 'currency' => 'MXN'],
        ['code' => 'ZA', 'name' => 'South Africa', 'currency' => 'ZAR'],
        ['code' => 'KR', 'name' => 'South Korea', 'currency' => 'KRW'],
        ['code' => 'HK', 'name' => 'Hong Kong', 'currency' => 'HKD'],
        ['code' => 'MY', 'name' => 'Malaysia', 'currency' => 'MYR'],
        ['code' => 'TH', 'name' => 'Thailand', 'currency' => 'THB'],
        ['code' => 'PK', 'name' => 'Pakistan', 'currency' => 'PKR'],
        ['code' => 'BD', 'name' => 'Bangladesh', 'currency' => 'BDT'],
        ['code' => 'EG', 'name' => 'Egypt', 'currency' => 'EGP'],
        ['code' => 'NG', 'name' => 'Nigeria', 'currency' => 'NGN'],
        ['code' => 'KE', 'name' => 'Kenya', 'currency' => 'KES'],
        ['code' => 'PH', 'name' => 'Philippines', 'currency' => 'PHP'],
        ['code' => 'ID', 'name' => 'Indonesia', 'currency' => 'IDR'],
        ['code' => 'VN', 'name' => 'Vietnam', 'currency' => 'VND'],
        ['code' => 'PL', 'name' => 'Poland', 'currency' => 'PLN'],
        ['code' => 'SE', 'name' => 'Sweden', 'currency' => 'SEK'],
        ['code' => 'CH', 'name' => 'Switzerland', 'currency' => 'CHF'],
        ['code' => 'RU', 'name' => 'Russia', 'currency' => 'RUB'],
        ['code' => 'TR', 'name' => 'Turkey', 'currency' => 'TRY'],
        ['code' => 'AR', 'name' => 'Argentina', 'currency' => 'ARS'],
        ['code' => 'CL', 'name' => 'Chile', 'currency' => 'CLP'],
        ['code' => 'CO', 'name' => 'Colombia', 'currency' => 'COP'],
        ['code' => 'NZ', 'name' => 'New Zealand', 'currency' => 'NZD'],
    ],
    'currencies' => [
        'USD' => 'US Dollar',
        'GBP' => 'British Pound',
        'EUR' => 'Euro',
        'INR' => 'Indian Rupee',
        'AUD' => 'Australian Dollar',
        'CAD' => 'Canadian Dollar',
        'JPY' => 'Japanese Yen',
        'CNY' => 'Chinese Yuan',
        'SGD' => 'Singapore Dollar',
        'AED' => 'UAE Dirham',
        'SAR' => 'Saudi Riyal',
        'BRL' => 'Brazilian Real',
        'MXN' => 'Mexican Peso',
        'ZAR' => 'South African Rand',
        'KRW' => 'South Korean Won',
        'HKD' => 'Hong Kong Dollar',
        'MYR' => 'Malaysian Ringgit',
        'THB' => 'Thai Baht',
        'PKR' => 'Pakistani Rupee',
        'BDT' => 'Bangladeshi Taka',
        'EGP' => 'Egyptian Pound',
        'NGN' => 'Nigerian Naira',
        'KES' => 'Kenyan Shilling',
        'PHP' => 'Philippine Peso',
        'IDR' => 'Indonesian Rupiah',
        'VND' => 'Vietnamese Dong',
        'PLN' => 'Polish Zloty',
        'SEK' => 'Swedish Krona',
        'CHF' => 'Swiss Franc',
        'RUB' => 'Russian Ruble',
        'TRY' => 'Turkish Lira',
        'ARS' => 'Argentine Peso',
        'CLP' => 'Chilean Peso',
        'COP' => 'Colombian Peso',
        'NZD' => 'New Zealand Dollar',
    ],
    'time_formats' => [
        '24h' => '24-hour (e.g. 14:30)',
        '12h' => '12-hour AM/PM (e.g. 2:30 PM)',
        '24h_sec' => '24-hour with seconds (e.g. 14:30:00)',
        '12h_sec' => '12-hour with seconds (e.g. 2:30:00 PM)',
    ],
];
